# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(455, 382)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(60, 200, 51, 51))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(130, 200, 51, 51))
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(200, 200, 51, 51))
        self.button3.setObjectName("button3")
        self.button6 = QtWidgets.QPushButton(self.centralwidget)
        self.button6.setGeometry(QtCore.QRect(200, 140, 51, 51))
        self.button6.setObjectName("button6")
        self.button5 = QtWidgets.QPushButton(self.centralwidget)
        self.button5.setGeometry(QtCore.QRect(130, 140, 51, 51))
        self.button5.setObjectName("button5")
        self.button4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4.setGeometry(QtCore.QRect(60, 140, 51, 51))
        self.button4.setObjectName("button4")
        self.button9 = QtWidgets.QPushButton(self.centralwidget)
        self.button9.setGeometry(QtCore.QRect(200, 80, 51, 51))
        self.button9.setObjectName("button9")
        self.button8 = QtWidgets.QPushButton(self.centralwidget)
        self.button8.setGeometry(QtCore.QRect(130, 80, 51, 51))
        self.button8.setObjectName("button8")
        self.button7 = QtWidgets.QPushButton(self.centralwidget)
        self.button7.setGeometry(QtCore.QRect(60, 80, 51, 51))
        self.button7.setObjectName("button7")
        self.button0 = QtWidgets.QPushButton(self.centralwidget)
        self.button0.setGeometry(QtCore.QRect(60, 260, 51, 51))
        self.button0.setObjectName("button0")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(280, 260, 51, 51))
        self.add.setObjectName("add")
        self.division = QtWidgets.QPushButton(self.centralwidget)
        self.division.setGeometry(QtCore.QRect(280, 80, 51, 51))
        self.division.setObjectName("division")
        self.subtract = QtWidgets.QPushButton(self.centralwidget)
        self.subtract.setGeometry(QtCore.QRect(280, 200, 51, 51))
        self.subtract.setObjectName("subtract")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(280, 140, 51, 51))
        self.multiply.setObjectName("multiply")
        self.equals = QtWidgets.QPushButton(self.centralwidget)
        self.equals.setGeometry(QtCore.QRect(340, 260, 51, 51))
        self.equals.setObjectName("equals")
        self.Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Delete.setGeometry(QtCore.QRect(130, 260, 51, 51))
        self.Delete.setObjectName("Delete")
        self.allClear = QtWidgets.QPushButton(self.centralwidget)
        self.allClear.setGeometry(QtCore.QRect(200, 260, 51, 51))
        self.allClear.setObjectName("allClear")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 15, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAcceptDrops(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.square = QtWidgets.QPushButton(self.centralwidget)
        self.square.setGeometry(QtCore.QRect(340, 140, 51, 51))
        self.square.setObjectName("square")
        self.mod = QtWidgets.QPushButton(self.centralwidget)
        self.mod.setGeometry(QtCore.QRect(340, 200, 51, 51))
        self.mod.setObjectName("mod")
        self.pi = QtWidgets.QPushButton(self.centralwidget)
        self.pi.setGeometry(QtCore.QRect(340, 80, 51, 51))
        self.pi.setObjectName("pi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button0.clicked.connect(lambda: self.clicked("0"))
        self.button1.clicked.connect(lambda: self.clicked("1"))
        self.button2.clicked.connect(lambda: self.clicked("2"))
        self.button3.clicked.connect(lambda: self.clicked("3"))
        self.button4.clicked.connect(lambda: self.clicked("4"))
        self.button5.clicked.connect(lambda: self.clicked("5"))
        self.button6.clicked.connect(lambda: self.clicked("6"))
        self.button7.clicked.connect(lambda: self.clicked("7"))
        self.button8.clicked.connect(lambda: self.clicked("8"))
        self.button9.clicked.connect(lambda: self.clicked("9"))
        
        self.add.clicked.connect(lambda: self.clicked("+"))
        self.division.clicked.connect(lambda: self.clicked("/"))
        self.subtract.clicked.connect(lambda: self.clicked("-"))
        self.multiply.clicked.connect(lambda: self.clicked("*"))
        self.equals.clicked.connect(lambda: self.clicked("="))     # self check
        self.square.clicked.connect(lambda: self.clicked("^"))     # self check
        self.mod.clicked.connect(lambda: self.clicked("%"))
        self.pi.clicked.connect(lambda: self.clicked("<"))         # self check

        self.allClear.clicked.connect(lambda: self.clicked(":"))   # self check
        self.Delete.clicked.connect(lambda: self.clicked(";"))     # self check

    def lastChar(self) -> str:
        if (len(self.globalString) == 0): return ''
        return self.globalString[len(self.globalString) - 1]

    def isLastCharOperator(self):
        return 1 if self.lastChar() in self.globalSet1 else 0

    def globalStr(self, string):
        self.globalString = string
        self.globalSet1 = {'+', '/', '-', '*', '=', '^', '%', '<', ':', ';', '.'}
        self.separateSet = {'+', '-'}

    # CAN'T PUT 900
    def clicked(self, text):
        if (len(self.globalString) == 1 and self.globalString[0] == '0'):
            # text.isdigit() and \
            #self.globalString.isdigit() and int(self.globalString) == 0):
            self.globalString = ''
        if len(self.globalString) > 0:
            if not(self.isLastCharOperator()):
                if text == '^':
                    self.globalString += '**2'
                elif text == '=':
                    self.equal()
        if text == '<':
            if len(self.globalString) == 0 or self.isLastCharOperator() and self.lastChar() != '.':
                self.globalString += str(round(math.pi, 4))
        elif text == ';':
            self.delete()
        elif text == ':':
            self.clearing()         # cab + c
        elif text.isdigit() or text == '-' or (len(self.globalString) > 0 and not(self.isLastCharOperator())):
            if text.isdigit() and self.lastChar() != '0' or text != '=' and text != '^' and self.lastChar() != '0' and self.lastChar() != '-' or (self.lastChar() != '-' and text in self.separateSet):
                self.globalString += text
        self.update()

    def clearing(self):
        self.globalString = ''

    def delete(self):
        if len(self.globalString) != 0:
            self.globalString = self.globalString[:len(self.globalString) - 1]
    
    def equal(self):
        if not(self.isLastCharOperator()):
            x = eval(self.globalString)
            x = str(round(x, 5))
            if x.endswith('.0'):
                x = x[:-2]
            self.globalString = x
    
    def update(self):
        print(self.globalString)
        self.globalString = str(self.globalString)
        self.label.setText(self.globalString)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button0.setText(_translate("MainWindow", "0"))
        self.add.setText(_translate("MainWindow", "+"))
        self.division.setText(_translate("MainWindow", "/"))
        self.subtract.setText(_translate("MainWindow", "-"))
        self.multiply.setText(_translate("MainWindow", "*"))
        self.equals.setText(_translate("MainWindow", "="))
        self.Delete.setText(_translate("MainWindow", "Del"))
        self.allClear.setText(_translate("MainWindow", "AC"))
        self.label.setText(_translate("MainWindow", ""))
        self.square.setText(_translate("MainWindow", "a**2"))
        self.mod.setText(_translate("MainWindow", "%"))
        self.pi.setText(_translate("MainWindow", "pi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.globalStr('')
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
